const products = [
  {
    category: "Cereals",
    name: "Wheat",
    package: [5, 10, 40],
    price: 25,
    unit: "kg",
    details: "Best quatity Wheat!!",
  },
  {
    category: "Cereals",
    name: "Rice",
    package: [5, 10, 25],
    price: 40,
    unit: "kg",
    details: "Best quatity Wheat!!",
  },
  {
    category: "Cereals",
    name: "Bajra",
    package: [5, 10, 25],
    price: 30,
    unit: "kg",
    details: "Best quatity Bajra!!",
  },
  {
    category: "Cereals",
    name: "Maize",
    package: [5, 10, 25],
    price: 30,
    unit: "kg",
    details: "Best quatity Bajra!!",
  },
  {
    category: "Dry Fruit",
    name: "Almond",
    package: [200, 500],
    price: 100,
    unit: "g",
    details: "Best quatity Almond!!",
  },
  {
    category: "Dry Fruit",
    name: "Cashew",
    package: [200, 500],
    price: 125,
    unit: "g",
    details: "Best quatity Cashew!!",
  },
  {
    category: "Dry Fruit",
    name: "Pistachios",
    package: [200, 500],
    price: 150,
    unit: "g",
    details: "Best quatity Wheat!!",
  },
  {
    category: "Dry Fruit",
    name: "Raisin",
    package: [200, 500],
    price: 135,
    unit: "g",
    details: "Best quatity Raisin!!",
  },
  {
    category: "Oil",
    name: "GroundNut",
    package: [1, 5, 15],
    price: 80,
    unit: "lit",
    details: "Best quatity Ground Nut!!",
  },
  {
    category: "Oil",
    name: "Soyabean",
    package: [1, 5, 15],
    price: 60,
    unit: "lit",
    details: "Best quatity Soyabean!!",
  },
  {
    category: "Oil",
    name: "Seseame",
    package: [1, 5, 15],
    price: 80,
    unit: "lit",
    details: "Best quatity Sesame!!",
  },
  {
    category: "Oil",
    name: "Mustard",
    package: [1, 5, 15],
    price: 100,
    unit: "lit",
    details: "Best quatity Musturd!!",
  },
  {
    category: "Pulses",
    name: "Red Gram",
    package: [1, 5, 10],
    price: 120,
    unit: "g",
    details: "Best quatity RedGram!!",
  },
  {
    category: "Pulses",
    name: "Beans",
    package: [1, 5, 10],
    price: 100,
    unit: "g",
    details: "Best quatity Beans!!",
  },
  {
    category: "Pulses",
    name: "Bengal Gram",
    package: [1, 5, 10],
    price: 110,
    unit: "g",
    details: "Best quatity Bengal Gram!!",
  },
  {
    category: "Pulses",
    name: "Black Gram",
    package: [1, 5, 10],
    price: 114,
    unit: "g",
    details: "Best quatity Black Gram!!",
  },
  {
    category: "Pulses",
    name: "Green Peas",
    package: [1, 5, 10],
    price: 124,
    unit: "g",
    details: "Best quatity Green Peas!!",
  },
  {
    category: "Pulses",
    name: "Green Peas",
    package: [1, 5, 10],
    price: 105,
    unit: "g",
    details: "Best quatity Green Peas!!",
  },
  {
    category: "Pulses",
    name: "Masur Dal",
    package: [1, 5, 10],
    price: 112,
    unit: "g",
    details: "Best quatity Masur Dal!!",
  },
];
export default products;
